name: SchellCode
description: "Code knowhow and stuff I've discovered"
markdown: redcarpet
highlighter: pygments
pygments: true
paginate: 5
permalink: /:title
rss-feed-limit: 10
rss-show-full: "no"
with_toc_data: true
